variables:
  ###
  # IMPORTANT
  # These are the version tags for the docker images the CI runs against.
  # If you are hacking on them or need a them to rebuild, its enough
  # to change any part of the string of the image you want.
  ###
  FEDORA_TAG:  '2023-04-26.0'
  INDENT_TAG: '2023-03-16.1'
  LINT_TAG: '2023-02-16.5'
  WINDOWS_TAG: '2023-04-21.0'
